/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { AcademicPaper, UserProfile, WikipediaEdit, GlobalSettings, SentEmail } from './types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'HD-USR-00001',
    email: 'mabrouk@dr.com',
    name: 'Dr. Mabrouk Al-Hadi',
    nameAR: 'أ.د. مبروك الهادي',
    institution: 'University of Health Sciences & Medical Research',
    institutionAR: 'جامعة العلوم الصحية والبحوث الطبية',
    role: 'admin',
    isPublic: true,
    contributionsCount: 18,
    registeredAt: '2024-01-12',
    bio: 'Chief Academic Director and Senior Advisor in Cardiovascular Epidemiology. Overseeing Healthdia.org global operations.',
    bioAR: 'المدير الأكاديمي العام ومستشار أول لأبحاث وبائيات القلب والأوعية الدموية. المشرف العام على منصة هيلثديا الأكاديمية.',
    username: 'mabrouk',
    password: 'MabroukSecure123',
    credentials: 'M.D., F.A.C.C., Senior Consultant Cardiology',
    credentialsAR: 'دكتوراه في الطب البشري، زميل الجمعية الأمريكية لأمراض القلب، مستشار أول',
    professionalHistory: '20+ Years in Cardiovascular Epidemiology, Al-Hadi Heart Center & Univ of Health Sciences. Peer committee leader.',
    professionalHistoryAR: 'أكثر من ٢٠ سنة في وبائيات القلب والأوعية الدموية بمركز الهادي للقلب وجامعة العلوم الصحية.',
    
    // Configured parameters
    isEmailDomainVerified: true,
    isDigitallyVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200',
    academicMetrics: { citations: 1542, hIndex: 24, papersCount: 18 },
    orcidId: '0000-0002-1823-9124',
    pubmedId: 'M-9241-2024',
    googleScholarId: 's7a8A9gAAAAJ',
    verificationIDStatus: 'verified'
  },
  {
    id: 'HD-USR-10042',
    email: 'sarah.j@healthdia.org',
    name: 'Dr. Sarah Jenkins',
    nameAR: 'د. سارة جينكينز',
    institution: 'Royal College of Endocrinology',
    institutionAR: 'الكلية الملكية لأمراض الغدد الصماء',
    role: 'editor',
    isPublic: true,
    contributionsCount: 42,
    registeredAt: '2024-03-05',
    bio: 'Associate Professor of Metabolic Health. Lead Editor of the Healthdia Scholarly Journal.',
    bioAR: 'أستاذ مشارك في الصحة الأيضية. رئيس تحرير مجلة هيلثديا العلمية للأبحاث.',
    username: 'sarahj',
    password: 'SarahJenkins_Crypto44',
    credentials: 'PhD in Endocrinology, MRCP (UK)',
    credentialsAR: 'دكتوراه في الغدد الصم والسكري، عضو الكلية الملكية للأطباء بالمملكة المتحدة',
    professionalHistory: 'Associate Researcher, Oxford Metabolic Unit 2015-2020. Senior Lead Editor Healthdia Journal.',
    professionalHistoryAR: 'باحث مشارك بوحدة أكسفورد للأيض ٢٠١٥-٢٠٢٠. رئيس تحرير معتمد بمجلة هيلثديا.',
    
    isEmailDomainVerified: true,
    isDigitallyVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=200',
    academicMetrics: { citations: 894, hIndex: 16, papersCount: 11 },
    orcidId: '0000-0003-9421-5524',
    pubmedId: 'J-1024-2023',
    googleScholarId: 't8X9B8oAAAAJ',
    verificationIDStatus: 'verified'
  },
  {
    id: 'HD-USR-22841',
    email: 'ahmad.m@univ.edu',
    name: 'Ahmad Al-Masri, PhD',
    nameAR: 'د. أحمد المصري',
    institution: 'Alexandria Faculty of Medicine',
    institutionAR: 'كلية الطب بجامعة الإسكندرية',
    role: 'researcher',
    isPublic: true,
    contributionsCount: 9,
    registeredAt: '2025-01-20',
    bio: 'Lead Clinical Researcher specializing in SGLT2 inhibitors and diabetic nephropathy pathways.',
    bioAR: 'باحث عيادي رئيسي متخصص في مثبطات SGLT2 ومسارات اعتلال الكلية السكري والمؤشرات الحيوية.',
    username: 'ahmad_m',
    password: 'AlMasriResearcher99',
    credentials: 'Ph.D. in Cellular Biochemistry',
    credentialsAR: 'دكتوراه في الكيمياء الحيوية الخلوية',
    professionalHistory: 'Senior Lecturer, Alexandria Faculty of Medicine. Expert in diabetic renal biomarkers.',
    professionalHistoryAR: 'محاضر أول بكلية الطب جامعة الإسكندرية. خبير في المؤشرات الحيوية للكلى لمرضى السكري.',
    
    isEmailDomainVerified: true,
    isDigitallyVerified: false,
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200',
    academicMetrics: { citations: 98, hIndex: 6, papersCount: 3 },
    orcidId: '0000-0001-4912-8822',
    googleScholarId: 'u7Y2X9oAAAAJ',
    verificationIDStatus: 'pending',
    uploadedIDUrl: 'https://images.unsplash.com/photo-1554774853-aae0a22c8aa4?auto=format&fit=crop&q=80&w=400',
    uploadedPassportUrl: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&q=80&w=400',
    extractedVerificationData: {
      extractedName: 'Ahmad Al-Masri',
      extractedInstitution: 'Alexandria Faculty of Medicine',
      nameMatched: true,
      institutionMatched: true,
      confidence: 97
    }
  },
  {
    id: 'HD-USR-99402',
    email: 'layla.m@student.net',
    name: 'Layla Mahmoud',
    nameAR: 'ليلى محمود',
    institution: 'Cairo Medical University',
    institutionAR: 'جامعة القاهرة بكلية الطب والتمريض',
    role: 'student',
    isPublic: false,
    contributionsCount: 2,
    registeredAt: '2026-02-14',
    bio: 'Medical resident studying automated early diagnostics using convolutional neural networks.',
    bioAR: 'طبيبة مقيمة تدرس التشخيص المبكر الآلي باستخدام الشبكات العصبية الالتفافية.',
    username: 'laylam',
    password: 'LaylaMedStudent_2026',
    credentials: 'B.Sc. Medical Sciences (Candidate)',
    credentialsAR: 'بكالوريوس العلوم الطبية والجراحة متوقع ٢٠٢٦',
    professionalHistory: 'Clinical intern at Cairo Medical University. Researcher in health artificial neural systems.',
    professionalHistoryAR: 'طبيب امتياز عيادي بمستشفيات جامعة القاهرة. باحثة في الأنظمة العصبية الاصطناعية الصحية.',
    
    isEmailDomainVerified: false,
    isDigitallyVerified: false,
    academicMetrics: { citations: 12, hIndex: 2, papersCount: 1 },
    verificationIDStatus: 'none'
  }
];

export const INITIAL_PAPERS: AcademicPaper[] = [
  {
    id: 'HD-RES-84021',
    titleEN: 'Efficacy of SGLT2 Inhibitors on Cardiovascular Endpoints in Diabetic Patients: A Meta-Analysis of Randomized Clinical Trials',
    titleAR: 'فعالية مثبطات SGLT2 على المؤشرات القلبية الوعائية لدى مرضى السكري: تحليل تلوّي للتجارب العيادية العشوائية',
    abstractEN: 'Sodium-glucose cotransporter 2 (SGLT2) inhibitors have transitioned from glucose-lowering therapies to major cardioprotective modalities. This meta-analysis evaluates therapeutic efficacy across five high-profile computerized randomized controlled trials (RCTs). We analyzed composite rates of major adverse cardiovascular events (MACE), heart failure hospitalizations, and cardiovascular-related mortality. Outcomes consistently show a significant 14% relative risk reduction in MACE and a 31% reduction in hospitalization for acute heart failure, establishing SGLT2 inhibitors as primary targets for baseline guideline modifications.',
    abstractAR: 'انتقلت مثبطات ناقل الصوديوم والجلوكوز المشترك 2 (SGLT2) من كونها مجرد علاجات لخفض نسبة الجلوكوز في الدم إلى وسائل رئيسية لحماية القلب والأوعية الدموية. يقيم هذا التحليل التلوي الكفاءة العلاجية عبر خمس تجارب عشوائية ذات شواهد عالية المستوى. قمنا بتحليل المعدلات المركبة للأحداث القلبية الوعائية الضائرة الكبرى (MACE)، والاستشفاء بسبب قصور القلب، والوفيات المرتبطة بالقلب والأوعية الدموية. تظهر النتائج باستمرار انخفاضاً معنوياً بنسبة 14٪ في المخاطر النسبية لـ MACE وانخفاضاً بنسبة 31٪ في الاستشفاء لفشل القلب الحاد، مما يثبت دور مثبطات SGLT2 كخيار أولي.',
    authorsEN: ['Ahmad Al-Masri', 'Dr. Sarah Jenkins', 'Hassan K. Yousif'],
    authorsAR: ['أحمد المصري', 'د. سارة جينكينز', 'حسن ك. يوسف'],
    journalEN: 'Healthdia Journal of Cardiology & Metabolic Health',
    journalAR: 'مجلة هيلثديا لأمراض القلب والصحة الأيضية',
    publishedAt: '2025-08-11',
    categoryEN: 'Cardiology & Diabetes',
    categoryAR: 'أمراض القلب والسكري',
    doi: '10.58210/hd.2025.84021',
    methodologyEN: 'The research gathered data from five randomized, double-blind trials featuring 34,120 participants. Databases utilized include Medline, PubMed, and Embase, dating from 2018 up to May 2025. Statistical computation was executed using a random-effects meta-regression model. Heterogeneity was calculated employing Higgins I² statistical evaluation metrics.',
    methodologyAR: 'جمعت الدراسة بيانات من خمس تجارب عشوائية مزدوجة التعمية شملت 34,120 مشاركاً. تشمل قواعد البيانات المستخدمة Medline و PubMed و Embase الممتدة من عام 2018 حتى مايو 2025. تم إجراء الحساب الإحصائي باستخدام نموذج الانحدار التلوي ذي التأثيرات العشوائية. وحُسب عدم التجانس باستخدام مقياس Higgins I² الإحصائي للتقييم.',
    resultsEN: 'SGLT2 pathways demonstrated prominent cardiorenal safety. Hazard ratio was optimized at 0.86 (95% Confidence Interval: 0.80-0.92) for MACE outcomes. Furthermore, renal decline progression dropped significantly across the treatment group with minimal reported urinary infection risk. Mortality metrics highlighted an overall reduction in cardiovascular-related deaths across clinical indicators.',
    resultsAR: 'أظهرت مسارات SGLT2 سلامة قلبية كلوية واعدة للغاية. حيث وصل معدل الخطر المرجح إلى 0.86 (بفاصل ثقة 95٪: 0.80-0.92) لنتائج أحداث MACE. وعلاوة على ذلك، انخفض معدل تدهور وظائف الكلى بشكل كبير لدى المجموعة المعالجة مع أدنى مستويات مخاطر التهاب المسالك البولية. كما سلطت مؤشرات الوفيات المحسوبة الضوء على انخفاض عام في الوفيات القلبية الوعائية.',
    discussionEN: 'The therapeutic utility of SGLT2 inhibitors is independent of baseline glycemic control, indicating non-glycemic metabolic pathways. Our findings strongly endorse updated clinical policies to prescribe SGLT2 inhibitors as standard-of-care frontlines for heart failure risk mitigations in all adult patients diagnosed with Type-2 Diabetes.',
    discussionAR: 'الفائدة العلاجية لمثبطات SGLT2 مستقلة عن مستوى التحكم في نسبة السكر في الدم، مما يشير إلى وجود مسارات أيضية مميزة غير معنية بالجلوكوز فقط. تدعم نتائجنا بقوة السياسات السريرية المحدثة لوصف مثبطات SGLT2 كخط دفاع وقائي أول للحد من مخاطر فشل القلب لدى جميع المرضى البالغين المصابين بداء السكري من النوع الثاني.',
    citationCount: 48,
    views: 1250,
    downloads: 384,
    status: 'approved',
    submittedBy: 'HD-USR-22841',
    submittedByName: 'Ahmad Al-Masri, PhD',
    keywordsEN: ['SGLT2 Inhibitors', 'Type-2 Diabetes', 'Cardiovascular Hospitalization', 'MACE Risk Reduction'],
    keywordsAR: ['مثبطات SGLT2', 'السكري من النوع الثاني', 'الاستشفاء المرتبط بالقلب', 'تقليل مخاطر MACE'],
    seoTitle: 'Efficacy of SGLT2 Inhibitors on Cardiovascular Endpoints',
    seoDescription: 'Read the comprehensive meta-analysis evaluating the relative risk reduction of SGLT2 inhibitors on coronary and heart failure outcomes in diabetic cohorts.'
  },
  {
    id: 'HD-RES-41804',
    titleEN: 'Machine Learning Paradigms for Early Screening and Grading of Diabetic Retinopathy in Public Healthcare Networks',
    titleAR: 'نماذج التعلم الآلي للفحص المبكر وتصنيف اعتلال الشبكية السكري في شبكات الرعاية الصحية العامة',
    abstractEN: 'Diabetic retinopathy remains a leading cause of preventable visual impairment globally. Early screening is highly limited by specialist ophthalmologist access. This paper presents a verified deep neural network architecture (RetinaNet-HD) utilizing automated grading of retinal fundus photographs. Tested on a diverse local cohort, our pipeline achieves 96.4% sensitivity and 94.2% specificity in distinguishing mild non-proliferative stages from healthy controls, showing the massive potential of public integration.',
    abstractAR: 'لا يزال اعتلال الشبكية السكري سبباً رئيسياً لضعف البصر الذي يمكن الوقاية منه على مستوى العالم. ويعوق الفحص المبكر ندرة أطباء العيون المتخصصين في المناطق النائية. تقدم هذه الورقة بنية عصبية عميقة ومتحقق منها (RetinaNet-HD) تستخدم التصنيف الآلي لصور قاع العين الشبكية. حقق نموذجنا المبرمج حساسية تبلغ 96.4٪ ونوعية تبلغ 94.2٪ في تمييز المراحل غير التكاثرية الطفيفة مقارنة بالفئة السليمة، مما يثبت إمكانية التكامل الوقائي العام.',
    authorsEN: ['Layla Mahmoud', 'Dr. Sarah Jenkins'],
    authorsAR: ['ليلى محمود', 'د. سارة جينكينز'],
    journalEN: 'Healthdia Scholarly Journal of Medical Artificial Intelligence',
    journalAR: 'مجلة هيلثديا العلمية للذكاء الاصطناعي الطبي',
    publishedAt: '2026-02-18',
    categoryEN: 'Medical AI & Ophthalmology',
    categoryAR: 'الذكاء الاصطناعي الطبي وطب العيون',
    doi: '10.58210/hd.2026.41804',
    methodologyEN: 'We compiled a high-performance training dataset of 12,024 fundus files sourced from Cairo Medical University public registries. Retinal features were segmentally isolated using adaptive histogram equalization. We engineered a customized Convolutional Neural Network (CNN) incorporating ResNet50 as a primary backbone with transfer learning classifiers.',
    methodologyAR: 'قمنا بتجميع مجموعة بيانات تدريب عالية الأداء مكونة من 12,024 ملفاً لقاع الشبكية من السجلات العامة بمستشفى جامعة القاهرة. تم عزل معالم الشبكية بدقة بالاستعانة بمستويات تباين متكيفة للرسم البياني. قمنا بهندسة شبكة عصبية تلافيفية مخصصة (CNN) تدمج خوارزمية ResNet50 كعمود فقري رئيسي مع مصنفات نقل التعلم.',
    resultsEN: 'The deep learning approach achieved a stellar Area Under ROC curve (AUC-ROC) score of 0.982. Comparative testing against board-certified clinical retina specialists proved the software matched expert grading decisions in 95.1% of random multi-cohort challenges, significantly reducing screening throughput wait-times from days to milliseconds.',
    resultsAR: 'حقق نهج التعلم العميق درجة ممتازة في تقييم المساحة تحت منحنى ROC قدرها 0.982. وأثبتت الاختبارات المقارنة ضد أخصائيي شبكية سريريين حاصلين على البورد أن البرنامج يطابق قرارات التصنيف المعتمدة من الخبراء في 95.1٪ من التحديات، مما يقلل بشكل كبير وقت انتظار الفحص من أيام إلى أجزاء من الثانية.',
    discussionEN: 'Deploying automated RetinaNet engines in primary care clinics offers an actionable solution to scale screening capability without demanding ophthalmologist physical attendance. We advise deploying this open-source architecture in mobile wellness clinics serving high-risk regional zones.',
    discussionAR: 'إن نشر محركات RetinaNet المؤتمتة في عيادات الرعاية الأولية يقدم حلاً عملياً فعالاً لزيادة قدرات الفحص والفرز دون تطلب الحضور الجسدي لأخصائي العيون. نوصي بنشر هذه البنية مفتوحة المصدر في العيادات الصحة المتنقلة التي تخدم المناطق ذات الخطورة العالية للوقاية من فقدان البصر.',
    citationCount: 12,
    views: 890,
    downloads: 215,
    status: 'approved',
    submittedBy: 'HD-USR-99402',
    submittedByName: 'Layla Mahmoud',
    keywordsEN: ['Machine Learning', 'Ophthalmology', 'Diabetic Retinopathy', 'Computerized Diagnostics'],
    keywordsAR: ['التعلم الآلي', 'طب العيون', 'اعتلال الشبكية السكري', 'التشخيص الحاسوبي الآلي'],
    seoTitle: 'Diabetic Retinopathy Screening using Convolutional Neural Networks',
    seoDescription: 'Explore the high-performance deep learning CNN framework and RetinaNet architecture designed for automated clinical grading of retinal fundus photographs.'
  },
  {
    id: 'HD-RES-11290',
    titleEN: 'Preventive Epidemiological Frameworks for Acute Coronary Syndrome in Middle Eastern Climates',
    titleAR: 'الأطر الوبائية الوقائية لمتلازمة الشريان التاجي الحادة في مناخات الشرق الأوسط',
    abstractEN: 'Acute Coronary Syndrome (ACS) presents unique hazard clusters in the Middle East due to combined metabolic vulnerability and high ambient heat-stress triggers. This research investigates chronological incidence profiles over a 10-year period across three distinct regional healthcare networks. By correlating meteorological peaks with cardiovascular emergency visits, we propose a climate-aware clinical protocol aiming to protect patients through critical seasonal alert frameworks.',
    abstractAR: 'تبدي متلازمة الشريان التاجي الحادة (ACS) مجموعات خطر فريدة تماماً في منطقة الشرق الأوسط بسبب قابلية الإصابة الأيضية المشتركة ومستويات الإجهاد الحراري المحيط عالي التحفيز. يبحث هذا البحث في ملامح حدوث الحالات بشكل زمني على مدى فترة 10 سنوات عبر ثلاث شبكات رعاية صحية إقليمية متميزة. من خلال ربط الذرى الجوية لدرجات الحرارة مع زيارات الطوارئ القلبية، نقترح بروتوكولاً سريرياً يراعي المناخ لحماية المرضى.',
    authorsEN: ['Dr. Mabrouk Al-Hadi', 'Ahmad Al-Masri'],
    authorsAR: ['أ.د. مبروك الهادي', 'أحمد المصري'],
    journalEN: 'Middle Eastern Review of Epidemiological Research',
    journalAR: 'المجلة الشرق أوسطية لأبحاث الأوبئة وعلم الأوبئة',
    publishedAt: '2024-11-05',
    categoryEN: 'Public Health & Epidemiology',
    categoryAR: 'الصحة العامة وعلم الأوبئة',
    doi: '10.58210/hd.2024.11290',
    methodologyEN: 'We executed retrospective case-crossover studies of 11,400 cardiovascular hospital entries in regional cities. Met office databases supplied real-time heat indices with hourly variations. Time-stratified logistic models quantified cardiac exacerbation factors, accounting for age, history, smoking, and blood pressure factors.',
    methodologyAR: 'قمنا بإجراء دراسات تبادل الحالات بأثر رجعي لـ 11,400 حالة دخول قلبية وعائية في المستشفيات الإقليمية. زودتنا بيانات مكاتب الأرصاد بمؤشرات حرارية بالغة الدقة مع تسجيل تقلبات بالساعة. وقامت النماذج اللوجستية المصنفة زمنياً بتحديد عوامل تفاقم مشاكل القلب.',
    resultsEN: 'Our statistical cohort showcased a sharp positive trend of coronary incidents when temperature crossed 42°C (Relative Risk = 2.04, 95% Confidence Interval: 1.84-2.27). The vulnerability risk was three times higher in patients over 65 years who present pre-existing hypertension or active vascular inflammation.',
    resultsAR: 'أظهرت مجموعتنا الإحصائية اتجاهاً إيجابياً حاداً لحوادث الشرايين التاجية عندما تجاوزت درجة الحرارة 42 درجة مئوية (الخطر النسبي = 2.04، فاصل ثقة 95٪: 1.84-2.27). وكانت خطورة وعرضة الإصابة أعلى بثلاث مرات لدى المرضى الذين تزيد أعمارهم عن 65 عاماً ممن يعانون من ارتفاع هرموني أو ضغط شرياني.',
    discussionEN: 'We recommend incorporating localized "Cardio-Thermal Warning Alerts" into general public broadcasting. Public medical providers should adjust cardiovascular drug formulations—especially loop diuretics and ACE inhibitors—during intense high-heat spells to avoid thermal dehydration risks.',
    discussionAR: 'نوصي بدمج "تنبيهات الوقاية الحرارية القلبية" المترابطة محلياً في البث الإذاعي والتعليمي العام للجمهور. يجب على مقدمي الرعاية تعديل تركيبات أدوية القلب - وخاصة مدرات البول ومثبطات الإنزيم المحول للأنجيوتنسين - خلال فترات الحرارة الشديدة لتفادي الجفاف.',
    citationCount: 61,
    views: 1450,
    downloads: 502,
    status: 'approved',
    submittedBy: 'HD-USR-00001',
    submittedByName: 'Dr. Mabrouk Al-Hadi',
    keywordsEN: ['Epidemiology', 'Acute Coronary Syndrome', 'Heat Stress', 'Preventive Public Health'],
    keywordsAR: ['علم الأوبئة', 'متلازمة الشريان التاجي الحادة', 'الإجهاد الحراري', 'الصحة العامة الوقائية'],
    seoTitle: 'Preventive Cardiovascular Frameworks in Middle Eastern Climates',
    seoDescription: 'Discover the epidemiology linking cardiovascular coronary incidents to heat stress markers in arid regions, proposing localized cardio-thermal protective guidelines.'
  },
  {
    id: 'HD-RES-90124',
    titleEN: 'Clinical Assessment of Novel Oral Hypoglycemic Formulations in Pediatric Onset Diabetes Subtypes',
    titleAR: 'التقييم السريري لتركيبات خافضات سكر الدم الفموية الجديدة في الأنواع الفرعية لسكري الأطفال',
    abstractEN: 'Management of pediatric diabetes mellitus remains a therapeutic pain point, historically over-reliant on subcutaneous insulin. This clinical assessment observes glucose homeostasis, glycemic excursions, and early biomarker metrics over a 12-week trials of randomized, double-blind oral therapy (GlucaControl-V9). In pediatric cohorts, the therapy presented exceptional glycemic stabilization without inducing severe hypoglycemic collapses, providing a compelling option for mild early-onset phenotypes.',
    abstractAR: 'لا يزال تدبير مرض السكري لدى الأطفال يمثل معضلة علاجية صعبة، مع الاعتماد التاريخي المفرط على الأنسولين المحقون تحت الجلد. يرصد هذا التقييم السريري التوازن الهرموني ونوبات تذبذب سكر الدم ومؤشرات النضج البيولوجي المبكر على مدار 12 أسبوعاً من العلاج الفموي العشوائي ثنائي التعمية (GlucaControl-V9). يظهر استقراراً ممتازاً دون التسبب في هبوط حاد.',
    authorsEN: ['Ahmad Al-Masri', 'Dr. Sarah Jenkins', 'Layla Mahmoud'],
    authorsAR: ['أحمد المصري', 'د. سارة جينكينز', 'ليلى محمود'],
    journalEN: 'Healthdia Journal of Pediatrics and Endocrinology',
    journalAR: 'مجلة هيلثديا لطب أطفال وغدد صماء',
    publishedAt: '2026-05-10',
    categoryEN: 'Pediatric Endocrinology',
    categoryAR: 'غدد صم الأطفال',
    doi: '10.58210/hd.2026.90124',
    methodologyEN: 'Double-blind random screening was completed across 18 specialized pediatric medical institutes, observing 420 patients aged 8 to 14 years. GlucaControl-V9 was administered at 5mg doses once daily during major morning nutrition intake. Baseline and weekly glycated hemoglobin (HbA1c) were indexed closely.',
    methodologyAR: 'تم إجراء فحص عشوائي عيادي مزدوج التعمية في 18 معهداً طبياً تخصصياً للأطفال، حيث تمت مراقبة 420 مريضاً تتراوح أعمارهم بين 8 و14 عاماً. جرى إعطاء مركب GlucaControl-V9 بجرعات 5 ملغ مرة واحدة يومياً أثناء الوجبة الصباحية الرئيسية. وجرى تسجيل قيم التراكمي بدقة.',
    resultsEN: 'Average HbA1c reduced consistently by 1.15% (p < 0.001) in comparison to placebo control cohorts. Continuously monitored tissue glucose curves displayed reduced postprandial spikes by 24% without any serious safety incidents, severe metabolic ketoacidosis, or hepatic strain signs.',
    resultsAR: 'انخفض متوسط هيموجلوبين السكري التراكمي HbA1c بنسبة بلغت 1.15٪ (بمعنوية إحصائية p < 0.001) مقارنة بمجموعة الشواهد. وأظهرت منحنيات الجلوكوز النسيجية المراقبة باستمرار انخفاضاً ملحوظاً في القمم التي تلي تناول الطعام بنسبة 24٪ دون تسجيل أي مضاعفات كبدية.',
    discussionEN: 'The remarkable safety standard of GlucaControl-V9 suggests it can act as an alternate therapy or useful adjuvant to low-dose basal insulin regime. Pediatric clinical guidelines should study integrating non-injectable options to elevate general compliance and quality of life for diabetes sufferers.',
    discussionAR: 'يبشر معيار السلامة الممتاز لمركب GlucaControl-V9 عهداً جديداً كبديل أو مساند علاج أول لجرعات الأنسولين المنخفضة. يجب أن تدعو التوجيهات السريرية لدمج الحلول الفموية غير المحقونة لتعزيز مستويات التزام الأطفال المصابين بسكري الأطفال ورفع جودة حياتهم اليومية.',
    citationCount: 4,
    views: 310,
    downloads: 48,
    status: 'pending', // This will appear in the dashboard vetting queue!
    submittedBy: 'HD-USR-22841',
    submittedByName: 'Ahmad Al-Masri, PhD',
    keywordsEN: ['Pediatric Diabetes', 'Oral Hypoglycemics', 'HbA1c Reduction', 'Glycemic Homeostasis'],
    keywordsAR: ['سكري الأطفال', 'خافضات السكر الفموية', 'تقليل HbA1c التراكمي', 'توازن السكر في الدم'],
    seoTitle: 'Novel Oral Hypoglycemic Formulations in Pediatric Onset Diabetes',
    seoDescription: 'Read clinical assessments of pediatric diabetes management using non-injectable oral agents, focusing on postprandial glucose regulation and HbA1c stability.'
  }
];

export const INITIAL_EDITS: WikipediaEdit[] = [
  {
    id: 'HD-EDT-40124',
    paperId: 'HD-RES-84021',
    paperTitleEN: 'Efficacy of SGLT2 Inhibitors on Cardiovascular Endpoints in Diabetic Patients: A Meta-Analysis of Randomized Clinical Trials',
    paperTitleAR: 'فعالية مثبطات SGLT2 على المؤشرات القلبية الوعائية لدى مرضى السكري: تحليل تلوّي للتجارب العيادية العشوائية',
    suggestedBy: 'HD-USR-99402',
    suggestedByName: 'Layla Mahmoud',
    section: 'results',
    originalText: 'SGLT2 pathways demonstrated prominent cardiorenal safety. Hazard ratio was optimized at 0.86 (95% Confidence Interval: 0.80-0.92) for MACE outcomes. Furthermore, renal decline progression dropped significantly across the treatment group with minimal reported urinary infection risk. Mortality metrics highlighted an overall reduction in cardiovascular-related deaths across clinical indicators.',
    proposedText: 'SGLT2 pathways demonstrated prominent cardiorenal safety. Hazard ratio was optimized at 0.86 (95% Confidence Interval: 0.80-0.92) for MACE outcomes. Additionally, we noted a specific 28% decrease in combined endpoints of renal transplant or stage 5 kidney failure events (p = 0.003). Renoprotective profiles were highly pronounced in patients exhibiting baseline albuminuria, with no critical safety signals.',
    justification: 'Added precise glomerular and renal end-stage metrics from the DAPA-CKD trials to augment the general results description. Highly key since kidney protection is highly correlated to SGLT2 use.',
    createdAt: '2026-05-25',
    status: 'pending' // This will appear in the wiki edits verification queue!
  },
  {
    id: 'HD-EDT-10294',
    paperId: 'HD-RES-11290',
    paperTitleEN: 'Preventive Epidemiological Frameworks for Acute Coronary Syndrome in Middle Eastern Climates',
    paperTitleAR: 'الأطر الوبائية الوقائية لمتلازمة الشريان التاجي الحادة في مناخات الشرق الأوسط',
    suggestedBy: 'HD-USR-22841',
    suggestedByName: 'Ahmad Al-Masri, PhD',
    section: 'methodology',
    originalText: 'The research gathered data from regional cities.',
    proposedText: 'The research gathered data specifically from major regional centers including Cairo, Alexandria, Riyadh, and Jeddah to represent varying coastal and inland desert ambient climates.',
    justification: 'Specifying the exact cohort city names adds geographic precision for epidemiological accuracy.',
    createdAt: '2026-05-11',
    status: 'approved',
    reviewedBy: 'HD-USR-10042',
    reviewedByName: 'Dr. Sarah Jenkins',
    reviewedAt: '2026-05-12',
    editorFeedback: 'Approved edits. Highly accurate regional representation is key.'
  }
];

export const INITIAL_EMAILS: SentEmail[] = [
  {
    id: 'HD-EML-74812',
    recipient: 'mabrouk@dr.com',
    subject: 'Welcome to Healthdia.org - Academic Identity Active',
    body: 'Dear Dr. Mabrouk Al-Hadi, your Master Administrator Credentials and certified scientific index number have been secured under ID HD-USR-00001. System is active.',
    sentAt: '2024-01-12',
    type: 'registration'
  },
  {
    id: 'HD-EML-94012',
    recipient: 'ahmad.m@univ.edu',
    subject: 'Healthdia Scholarly Journal: Manuscript Accepted HD-RES-84021',
    body: 'Dear Dr. Ahmad Al-Masri, we are pleased to inform you that your academic manuscript "Efficacy of SGLT2 Inhibitors on Cardiovascular Endpoints" has passed triple-blind expert review and is now indexed dynamically.',
    sentAt: '2025-08-11',
    type: 'peer_review'
  },
  {
    id: 'HD-EML-10294',
    recipient: 'layla.m@student.net',
    subject: 'New Edit Suggestion Lodged for Vetting in Collaborative Wiki',
    body: 'Dear Layla Mahmoud, your proposed Wikipedia-Style revision for study HD-RES-84021 has been transmitted to Lead Editor Sarah Jenkins. You will receive an automated trigger once checked.',
    sentAt: '2026-05-25',
    type: 'submission'
  }
];

export const TRANSLATIONS = {
  en: {
    app_title: 'Healthdia',
    app_subtitle: 'The Ultimate Academic Research Hub',
    tagline: 'Connect. Explore. Advance Medical Knowledge.',
    academic_bank: 'Scholarly Repository & Global Peer-Reviewed Database',
    direction: 'ltr',
    font_family: 'Inter, sans-serif',
    
    // Auth & Navigation
    search: 'Search papers, categories, DOIs, authors...',
    search_placeholder: 'Try "SGLT2", "Retinopathy", "Mabrouk", "Diabetes" or DOI...',
    advanced_filters: 'Advanced Directory Filters',
    home: 'Home',
    browse: 'Repository',
    institutions: 'Institutions',
    dashboard: 'Admin Terminal',
    submissions: 'Submissions',
    login: 'Register Profile',
    register: 'Create Academic ID',
    logout: 'Exit Session',
    profile: 'My Academic Profile',
    academic_id: 'Academic Serial ID',
    unregistered: 'Vessel Session (Guest)',
    privacy_settings: 'Academic Visibility Context',
    public_visibility: 'Public Scholarly Portfolio (Discoverable)',
    private_visibility: 'Private Repository Access Only (Anonymized)',
    role: 'Scholarly Rank',
    change_role: 'Access Override (Simulated Rank)',
    institution: 'Affiliate Institute',
    bio: 'Academic Mission Abstract',
    registered_at: 'Registered',
    contributions: 'Scholarly Edits',
    save_profile: 'Update Academic Profile',

    // Search Engine
    search_cta: 'Explore Healthdia',
    search_sub: 'Searching across peer-reviewed clinical data, multi-tier journals, and wiki-edited medical databases',
    results_found: 'indexed papers matched queries',
    category: 'Scientific Discipline',
    citation_count: 'Citations',
    views: 'Abstract Views',
    downloads: 'PDF Downloads',
    published: 'Published On',
    read_more: 'Examine Full Study',
    no_results: 'No peer-reviewed papers cataloged under these criteria.',

    // Paper view & Wikipedia System
    academic_journal: 'Scholarly Journal Source',
    doi: 'Scholarly DOI',
    abstract: 'Abstract Structure',
    methodology: 'Data & Methodology',
    results: 'Analytical Results',
    discussion: 'Academic Discussion',
    suggest_wiki_edit: 'Propose Wikipedia Edit',
    edit_history: 'Revision Audit Trail',
    seo_preview: 'Search Engine Search Snippet (SEO Tool)',
    author: 'Primary Investigator',
    peer_reviewed: 'PEER-REVIEWED',
    academic_verification: 'VERIFIED REVISION',
    pending_verification: 'PENDING VERIFICATION',
    wikipedia_system_title: 'Wikipedia-style Collaborative Document Engine',
    wikipedia_system_desc: 'Community edits undergo strict multi-tier review before merging into the main scholarly consensus.',
    original_text: 'Current Scholarly Consent',
    proposed_text: 'Suggested Amendment Text',
    justification: 'Scholarly Rationale / Citation Source',
    submit_proposal: 'Launch Proof-of-Edit Proposal',
    propose_edit_for: 'Suggest revision for',
    edit_by: 'Revision proposal by',
    no_history: 'No cumulative revisions merged yet. This paper represents the baseline verified release.',

    // Submit Paper Form
    submit_new_paper: 'Submit Academic Discovery',
    title_en: 'Title (English)',
    title_ar: 'Title (Arabic)',
    abstract_en: 'Abstract (English)',
    abstract_ar: 'Abstract (Arabic)',
    authors_en: 'Authors (English, comma-separated)',
    authors_ar: 'Authors (Arabic, comma-separated)',
    journal_en: 'Target Journal (English)',
    journal_ar: 'Target Journal (Arabic)',
    category_en: 'Primary Discipline Class (English)',
    category_ar: 'Primary Discipline Class (Arabic)',
    methodology_en: 'Methodology Framework (English)',
    methodology_ar: 'Methodology Framework (Arabic)',
    results_en: 'Results Metrics (English)',
    results_ar: 'Results Metrics (Arabic)',
    discussion_en: 'Discussion & Implications (English)',
    discussion_ar: 'Discussion & Implications (Arabic)',
    keywords_en: 'Search Index Keywords (English, comma-separated)',
    keywords_ar: 'Search Index Keywords (Arabic, comma-separated)',
    submit_to_queue: 'Transmit to Editorial Review Queue',

    // Dashboard & Admin
    admin_dashboard_title: 'Global Administration & Peer-Vetting Desk',
    role_permissions: 'Audit Logs & Accounts',
    vetting_papers_queue: 'Peer-Review Manuscripts Vetting Queue',
    wiki_edits_queue: 'Multi-Tier Revision Proposal Queue',
    system_customization: 'Typography & Layout Calibration',
    no_pending_papers: 'Manuscript queue is clear of unverified entries.',
    no_pending_edits: 'All Wikipedia edit suggestions have been fully verified.',
    paper_status_updated: 'Paper status successfully updated to',
    edit_status_updated: 'Wikipedia audit status updated to',
    actions: 'Executive Action',
    approve: 'Approve & Index',
    reject: 'Reject Entry',
    add_feedback: 'Add Editorial Critique / Reason',
    save_settings: 'Apply Platform Tuning',
    user_accounts_title: 'Scientific Directory (Permissions & Forensic Traceability)',
    id_traceability: 'Forensic System ID tracking ensures direct accountability for community edits.',

    // SEO Meta Preview Tool
    seo_explainer: 'Below is a professional live simulation of how this scholarly paper is formatted for external crawlers and Google SERP displays.',
    google_preview: 'Google Search Result Preview',
    meta_title: 'Search Title Tag',
    meta_desc: 'Search Meta Description Description',
    canonical_url: 'Canonical Permanent URL',

    // Settings details
    typography_setup: 'Global Typography',
    font_serif: 'Elegant Editorial Serif (PT Serif / Playfair)',
    font_sans: 'Modern Swiss Sans-Serif (Inter / UI-Sans)',
    font_mono: 'Technical Technical Mono (Space Mono / JetBrains)',
    font_scale_title: 'Acoustic Font Scaling Factor',
    open_contribution_title: 'Wikipedia Mode Status',
    open_contrib_active: 'Allow community edit proposals from all registered Medical IDs',
    open_contrib_disabled: 'Lock database edit suggestions (Editorial Authority Only)',
    color_sheme_title: 'High-Contrast Monochromatic Theme Overrides',
    theme_monochrome: 'High-Contrast Monochromatic Light (Baseline standard)',
    theme_dark: 'Carbon Jet Black Monochromatic Dark (Low-Lux Environment)',
    theme_sand: 'Ancient Archival Sand Ink (Reading Mode)',

    // Alerts
    registration_success: 'New Academic Identity Provisioned! Welcome, Researcher.',
    submission_success: 'Academic manuscript safely transmitted to the vetting queue under ID',
    edit_success: 'Revision suggestion transmitted safely for Multi-Tier Peer checks under ID',
    review_success: 'Audit execution saved and applied to dataset.'
  },
  ar: {
    app_title: 'هيلثديا',
    app_subtitle: 'المستودع الرقمي لأبحاث الطب والعلوم',
    tagline: 'منصة عالمية لربط الباحثين وتوثيق ونشر المعرفة الطبية الموثوقة.',
    academic_bank: 'المستودع العلمي وقاعدة البيانات المحكمة دولياً',
    direction: 'rtl',
    font_family: 'Cairo, system-ui, sans-serif',

    // Auth & Navigation
    search: 'البحث في الأوراق العلمية، التخصصات، المعرفات DOI، الباحثين...',
    search_placeholder: 'ابحث عن "أحمد"، "مثبطات SGLT2"، "الشبكية"، "سكري" أو المعرف الرقمي...',
    advanced_filters: 'مرشحات الدليل الأكاديمي المتقدمة',
    home: 'الرئيسية',
    browse: 'مستودع الأبحاث',
    institutions: 'المؤسسات والمراكز',
    dashboard: 'منصة الإدارة والأرشفة',
    submissions: 'تقديم دراسة',
    login: 'إنشاء ملف أكاديمي',
    register: 'تسجيل هوية باحث',
    logout: 'إنهاء الجلسة',
    profile: 'الملف الأكاديمي الخاص بي',
    academic_id: 'الرقم التسلسلي الأكاديمي الموحد',
    unregistered: 'جلسة زائر (غير مسجل)',
    privacy_settings: 'سياق الخصوصية الأكاديمية والظهور',
    public_visibility: 'ملف باحث علني (ظاهر للباحثين والمؤسسات)',
    private_visibility: 'الوصول في سياق خاص (قراءة فقط بدون تتبع)',
    role: 'المرتبة الأكاديمية والامتيازات',
    change_role: 'تجاوز الصلاحيات (محاكاة المرتبة الأكاديمية)',
    institution: 'المؤسسة أو الجامعة التابع لها',
    bio: 'نبذة عن المسيرة والمجال البحثي',
    registered_at: 'تاريخ التسجيل',
    contributions: 'التاريخ التعديلي / المساهمات',
    save_profile: 'تحديث بيانات الهوية الأكاديمية',

    // Search Engine
    search_cta: 'استكشف منصة هيلثديا العلمية',
    search_sub: 'البحث والتحقق الفوري في قواعد البيانات الطبية، المخطوطات المحكمة، ومقترحات التعديل التشاركي',
    results_found: 'من الأوراق الطبية المفهرسة تطابقت مع معايير البحث',
    category: 'التخصص العلمي الدقيق',
    citation_count: 'الاقتباسات الموثقة',
    views: 'زيارات الملخص',
    downloads: 'مرات التحميل PDF',
    published: 'تاريخ النشر في المجلد',
    read_more: 'قراءة الدراسة الكاملة',
    no_results: 'لم نعثر على أي دراسات مطابقة لمعايير البحث المدخلة.',

    // Paper view & Wikipedia System
    academic_journal: 'المجلة العلمية المصدر',
    doi: 'المعرف الرقمي الدولي للمستند DOI',
    abstract: 'ملخص الدراسة وهيكليتها',
    methodology: 'البيانات ومنهجية العمل والتحليل',
    results: 'النتائج الإحصائية والتركيبية',
    discussion: 'المناقشة العلمية وتبعات التوصية',
    suggest_wiki_edit: 'تقديم مقترح تعديل ويكي تشاركي',
    edit_history: 'سجل تدقيق وتنقيح المراجعات الموثقة',
    seo_preview: 'معاينة محركات البحث وبطاقة الظهور الرقمي (SEO Tool)',
    author: 'الباحث والمحقق الرئيسي',
    peer_reviewed: 'دراسة محكمة علمياً',
    academic_verification: 'نسخة مراجعة ومعتمدة',
    pending_verification: 'تعديل معلق بانتظار الترشيح',
    wikipedia_system_title: 'منظومة التحرير التشاركي الهرمية (الويكي العلمي)',
    wikipedia_system_desc: 'تخضع المقترحات التعديلية لمراجعة متعددة الطبقات من الهيئات العلمية قبل دمجها بالدراسة الأصلية.',
    original_text: 'النص الأصلي المعتمد بالمسودة',
    proposed_text: 'النص المقترح للتعديل والإضافة',
    justification: 'المرجعية الأكاديمية والداعي العلمي للتوثيق',
    submit_proposal: 'تقديم طلب التعديل التشاركي',
    propose_edit_for: 'تقديم اقتراح تعديلي على دراسة',
    edit_by: 'اقتراح بواسطة الباحث ذو الهوية الرقمية',
    no_history: 'لم يتم الإقرار بأي تعديلات خارجية تشاركية حتى الآن لإصلاح المسودة المعتمدة الأساسية.',

    // Submit Paper Form
    submit_new_paper: 'تقديم دراسة وبحث علمي جديد للمجلة',
    title_en: 'العنوان (باللغة الإنجليزية)',
    title_ar: 'العنوان (باللغة العربية)',
    abstract_en: 'ملخص الدراسة (باللغة الإنجليزية)',
    abstract_ar: 'ملخص الدراسة (باللغة العربية)',
    authors_en: 'المؤلفون والمشاركون (باللغة الإنجليزية، مفصولين بفاصلة)',
    authors_ar: 'المؤلفون والمشاركون (باللغة العربية، مفصولين بفاصلة)',
    journal_en: 'المجلة المستهدفة للنشر (باللغة الإنجليزية)',
    journal_ar: 'المجلة المستهدفة للنشر (باللغة العربية)',
    category_en: 'التخصص العلمي الأساسي (باللغة الإنجليزية)',
    category_ar: 'التخصص العلمي الأساسي (باللغة العربية)',
    methodology_en: 'منهجية الدراسة والبيانات (باللغة الإنجليزية)',
    methodology_ar: 'منهجية الدراسة والبيانات (باللغة العربية)',
    results_en: 'مخرجات البحث والتحليل (باللغة الإنجليزية)',
    results_ar: 'مخرجات البحث والتحليل (باللغة العربية)',
    discussion_en: 'الاستنتاجات والتوصيات (باللغة الإنجليزية)',
    discussion_ar: 'الاستنتاجات والتوصيات (باللغة العربية)',
    keywords_en: 'الكلمات المفتاحية للفهرسة (باللغة الإنجليزية، مفصولة بفاصلة)',
    keywords_ar: 'الكلمات المفتاحية للفهرسة (باللغة العربية، مفصولة بفاصلة)',
    submit_to_queue: 'إرسال المخطوط إلى طابور مراجعة المحكمين',

    // Dashboard & Admin
    admin_dashboard_title: 'مجلس الإدارة الأكاديمية والتحكيم والتدقيق',
    role_permissions: 'الأعضاء والتحقق الجنائي',
    vetting_papers_queue: 'مسودات الأبحاث الطبية المودعة بانتظار الاعتماد',
    wiki_edits_queue: 'المقترحات التشاركية المعلقة بانتظار تصويت المحررين',
    system_customization: 'تخصيص النظام والمعايرة والسمة البصرية',
    no_pending_papers: 'طابور الأبحاث الطبية فارغ من أي معاملات معلقة حالياً.',
    no_pending_edits: 'جميع المقترحات التشاركية المحررة تمت مراجعتها وفهرستها.',
    paper_status_updated: 'تم تحديث حالة الدراسة بنجاح إلى',
    edit_status_updated: 'تم تحديث حالة المراجعة التشاركية بنجاح إلى',
    actions: 'الإجراءات الإدارية',
    approve: 'تحكيم وإقرار (قبول)',
    reject: 'رفض المعاملة أو طلب تعديل',
    add_feedback: 'إضافة التعليق العلمي للمحكم / أسباب القرار',
    save_settings: 'حفظ وتطبيق إعدادات السمة والخطوط',
    user_accounts_title: 'سجل الهيئات والباحثين المسجلين (التتبع والأمان الأكاديمي)',
    id_traceability: 'يضمن الرقم التسلسلي الدائم الموحد لكل باحث تتبعاً جنائياً ونسبة التوثيقات والصفحات دون انتحال.',

    // SEO Meta Preview Tool
    seo_explainer: 'المعاين التالي يوضح كيف تظهر دراستك العلمية وبحوثك في نتائج غوغل ومحركات البحث الخارجية وفق قواعد السيو العالمية المتقدمة.',
    google_preview: 'محاكاة لصفحة نتائج غوغل العالمية',
    meta_title: 'عنوان السيو المخصص لنتائج البحث',
    meta_desc: 'الوصف التعريفي المقتضب لنتائج البحث السريعة (Meta Description)',
    canonical_url: 'الرابط الدائم المرجعي الموثق للدراسة',

    // Settings details
    typography_setup: 'المعاينة الخطية العالمية للنظام والطباعة',
    font_serif: 'خط ورقي تقليدي أنيق (Serif)',
    font_sans: 'خط عصري عملي للواجهات وقراءة الشاشة (Cairo / Sans)',
    font_mono: 'خط دقيق للرموز الإحصائية والكود (Mono)',
    font_scale_title: 'نسبة تكبير الخط للمقالات الطبية',
    open_contribution_title: 'نظام التحرير التشاركي المفتوح',
    open_contrib_active: 'تفعيل خيار المساهمة الويكي المفتوحة لحاملي الهويات العلمية',
    open_contrib_disabled: 'قصر حركية التعديل على رتبة المحرر والمدير فقط لدواعٍ أمنية',
    color_sheme_title: 'تخصيص سمة التباين الأحادي (الأبيض والأسود والرمادي الرصين)',
    theme_monochrome: 'الوضوح الأحادي الكلاسيكي (الأبيض والأسود الفاتح والرمادي الناعم)',
    theme_dark: 'السمة الأحادية الفحمية منخفضة الإضاءة (برية داكنة)',
    theme_sand: 'اللون الورقي الرملي الأثري المهدئ بصرداً (موضع القراءة المعتق القديم)',

    // Alerts
    registration_success: 'تم إصدار وتوثيق رقم الهوية الرقمية الأكاديمية بنجاح! مرحباً بالزميل الباحث.',
    submission_success: 'تم إيداع مسودة البحث بنجاح، وسجلت في طابور التدقيق والمحكمين بالرقم المرجعي الموحد',
    edit_success: 'تم إيداع مقترحك التحريري التشاركي، وسيتم تدقيقه هرمياً لمنع التزييف، المسجل برقم',
    review_success: 'تم معالجة الإجراء بنجاح وتحديث قاعدة البيانات الأكاديمية.'
  }
};
